-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE users (
--   "id" uuid PRIMARY KEY,
--   "name" TEXT,
--   "email" TEXT,
--   "firebaseId" TEXT,
--   "status" TEXT,
--   "avatar" TEXT,
--   "address" TEXT,
--   "phoneNumber" TEXT,
--   "isMuted" BOOLEAN,
--   "createdAt" TIMESTAMP DEFAULT now(),
--   "updatedAt" TIMESTAMP DEFAULT now()
-- );
--
-- CREATE TABLE dailyTasks (
--   "id" uuid PRIMARY KEY,
--   "userId" uuid,
--   "priority" TEXT,
--   "description" TEXT,
--   "date" TIMESTAMP,
--   "status" TEXT,
--   "taskStatus" TEXT,
--   "month" INTEGER,
--   "year" INTEGER,
--   "createdAt" TIMESTAMP DEFAULT now(),
--   "updatedAt" TIMESTAMP DEFAULT now(),
--   FOREIGN KEY ("userId") REFERENCES users("id")
-- );
--
-- CREATE TABLE notes (
--   "id" uuid PRIMARY KEY,
--   "userId" uuid REFERENCES users(id),
--   "title" TEXT,
--   "description" TEXT,
--   "createdAt" TIMESTAMP DEFAULT now(),
--   "updatedAt" TIMESTAMP DEFAULT now(),
--   "markedAsDone" BOOLEAN,
--   FOREIGN KEY ("userId") REFERENCES users("id")
-- );
